export const CHANGE_APP_TITLE = 'CHANGE_APP_TITLE';
export const AUTHENTICATE = 'AUTHENTICATE';
export const GET_LOCAL_WEATHER = 'GET_LOCAL_WEATHER';
export const GET_SEARCHED_CITY = 'GET_SEARCHED_CITY';
export const CURRENT_SAVED_CITY = 'CURRENT_SAVED_CITY';
