export const SET_CURRENT_CITY_ID = 'SET_CURRENT_CITY_ID';
export const CITIES_HAS_ERRORED = 'CITIES_HAS_ERRORED';
export const CITIES_ARE_LOADING = 'CITIES_ARE_LOADING';
export const CITIES_FETCH_DATA_SUCCESS = 'CITIES_FETCH_DATA_SUCCESS';
export const ICON_HEIGHT_BIG = '200px';
export const ICON_WIDTH_BIG = '200px';
export const ICON_HEIGHT_SMALL = '60px';
export const ICON_WIDTH_SMALL = '60px';
export const ICONS_PARAM = { "color": "orange" };