import type { LocationAllResponse } from 'types';

export enum ActionType {
  SEARCH_LOCATION_PENDING = 'SEARCH_LOCATION_PENDING',
  SEARCH_LOCATION_SUCCESS = 'SEARCH_LOCATION_SUCCESS',
  SEARCH_LOCATION_FAIL = 'SEARCH_LOCATION_FAIL',

  GET_LOCATION_INFO_PENDING = 'GET_LOCATION_INFO_PENDING',
  GET_LOCATION_INFO_SUCCESS = 'GET_LOCATION_INFO_SUCCESS',
  GET_LOCATION_INFO_FAIL = 'GET_LOCATION_INFO_FAIL',

  GET_LOCATION_CURRENT_WEATHER_PENDING = 'GET_LOCATION_CURRENT_WEATHER_PENDING',
  GET_LOCATION_CURRENT_WEATHER_SUCCESS = 'GET_LOCATION_CURRENT_WEATHER_SUCCESS',
  GET_LOCATION_CURRENT_WEATHER_FAIL = 'GET_LOCATION_CURRENT_WEATHER_FAIL',

  GET_LOCATION_HOURLY_WEATHER_PENDING = 'GET_LOCATION_HOURLY_WEATHER_PENDING',
  GET_LOCATION_HOURLY_WEATHER_SUCCESS = 'GET_LOCATION_HOURLY_WEATHER_SUCCESS',
  GET_LOCATION_HOURLY_WEATHER_FAIL = 'GET_LOCATION_HOURLY_WEATHER_FAIL',

  GET_LOCATION_THREE_HOURLY_WEATHER_PENDING = 'GET_LOCATION_THREE_HOURLY_WEATHER_PENDING',
  GET_LOCATION_THREE_HOURLY_WEATHER_SUCCESS = 'GET_LOCATION_THREE_HOURLY_WEATHER_SUCCESS',
  GET_LOCATION_THREE_HOURLY_WEATHER_FAIL = 'GET_LOCATION_THREE_HOURLY_WEATHER_FAIL',

  GET_LOCATION_DAILY_WEATHER_PENDING = 'GET_LOCATION_DAILY_WEATHER_PENDING',
  GET_LOCATION_DAILY_WEATHER_SUCCESS = 'GET_LOCATION_DAILY_WEATHER_SUCCESS',
  GET_LOCATION_DAILY_WEATHER_FAIL = 'GET_LOCATION_DAILY_WEATHER_FAIL',

  SET_LOCATION_QUERY = 'SET_LOCATION_QUERY'
}

interface ActionPending {
  type:
    | ActionType.SEARCH_LOCATION_PENDING
    | ActionType.GET_LOCATION_INFO_PENDING
    | ActionType.GET_LOCATION_CURRENT_WEATHER_PENDING
    | ActionType.GET_LOCATION_HOURLY_WEATHER_PENDING
    | ActionType.GET_LOCATION_THREE_HOURLY_WEATHER_PENDING
    | ActionType.GET_LOCATION_DAILY_WEATHER_PENDING;
}

interface ActionSuccess {
  type:
    | ActionType.SEARCH_LOCATION_SUCCESS
    | ActionType.GET_LOCATION_INFO_SUCCESS
    | ActionType.GET_LOCATION_CURRENT_WEATHER_SUCCESS
    | ActionType.GET_LOCATION_HOURLY_WEATHER_SUCCESS
    | ActionType.GET_LOCATION_THREE_HOURLY_WEATHER_SUCCESS
    | ActionType.GET_LOCATION_DAILY_WEATHER_SUCCESS;
  payload: LocationAllResponse;
}

interface ActionFail {
  type:
    | ActionType.SEARCH_LOCATION_FAIL
    | ActionType.GET_LOCATION_INFO_FAIL
    | ActionType.GET_LOCATION_CURRENT_WEATHER_FAIL
    | ActionType.GET_LOCATION_HOURLY_WEATHER_FAIL
    | ActionType.GET_LOCATION_THREE_HOURLY_WEATHER_FAIL
    | ActionType.GET_LOCATION_DAILY_WEATHER_FAIL;
  payload: string;
}

interface ActionQuery {
  type: ActionType.SET_LOCATION_QUERY;
  payload: string;
}

export type Action = ActionPending | ActionSuccess | ActionFail | ActionQuery;
