export type CurrentWeatherType = {
  current: {
    time: string;
    symbol: string;
    symbolPhrase: string;
    temperature: number;
    feelsLikeTemp: number;
    relHumidity: number;
    dewPoint: number;
    windSpeed: number;
    windDir: number;
    windDirString: string;
    windGust: number;
    precipProb: number;
    precipRate: number;
    cloudiness: number;
    thunderProb: number;
    uvIndex: number;
    pressure: number;
    visibility: number;
  };
};

export type HourlyWeatherType = {
  time: string;
  symbol: string;
  symbolPhrase: string;
  temperature: number;
  feelsLikeTemp: number;
  windSpeed: number;
  windGust: number;
  relHumidity: number;
  dewPoint: number;
  windDir: number;
  windDirString: string;
  precipProb: number;
  precipAccum: number;
  snowAccum: number;
  cloudiness: number;
  thunderProb: number;
  uvIndex: number;
  pressure: number;
  visibility: number;
  precipType: string;
  solarRadiation: number;
}[];

export type DailyWeatherType = {
  date: string;
  symbol: string;
  symbolPhrase: string;
  maxTemp: number;
  minTemp: number;
  maxFeelsLikeTemp: number;
  minFeelsLikeTemp: number;
  maxRelHumidity: number;
  minRelHumidity: number;
  maxDewPoint: number;
  minDewPoint: number;
  precipAccum: number;
  snowAccum: number;
  maxWindSpeed: number;
  windDir: number;
  maxWindGust: number;
  precipProb: number;
  cloudiness: number;
  sunrise: string;
  sunset: string;
  sunriseEpoch: number;
  sunsetEpoch: number;
  moonrise: string;
  moonset: string;
  moonPhase: number;
  uvIndex: number;
  minVisibility: number;
  pressure: number;
  confidence: string;
  solarRadiationSum: number;
}[];
