export const SET_IS_TOKEN_RECEIVED = 'SET_IS_TOKEN_RECEIVED';
export const SET_TOKEN_EXPIRATION_TIME = 'SET_TOKEN_EXPIRATION_TIME';
export const SET_IS_FETCHING_IN_PROGRESS = 'SET_IS_FETCHING_IN_PROGRESS';
export const SET_FETCHING_ERROR = 'SET_FETCHING_ERROR';

export const SET_THEME = 'SET_THEME';

export const SET_GEO_DETECTION_POSITION = 'SET_GEO_DETECTION_POSITION';
export const SET_GEO_DETECTION_ERROR = 'SET_GEO_DETECTION_ERROR';

export const SET_CURRENT_LOCATION_INFO = 'SET_CURRENT_LOCATION_INFO';
export const SET_CURRENT_LOCATION_WEATHER = 'SET_CURRENT_LOCATION_WEATHER';
export const SET_CURRENT_LOCATION_DAILY_WEATHER = 'SET_CURRENT_LOCATION_DAILY_WEATHER';
export const SET_CURRENT_LOCATION_DETAILED_WEATHER = 'SET_CURRENT_LOCATION_DETAILED_WEATHER';

export const ADD_SELECTED_LOCATION = 'ADD_SELECTED_LOCATION';
export const UPDATE_SELECTED_LOCATION = 'UPDATE_SELECTED_LOCATION';
export const PUT_SELECTED_LOCATION = 'PUT_SELECTED_LOCATION';
export const DELETE_SELECTED_LOCATION = 'DELETE_SELECTED_LOCATION';
export const CLEAR_SELECTED_LOCATIONS = 'CLEAR_SELECTED_LOCATIONS';

export const SET_SEARCH_QUERY = 'SET_SEARCH_QUERY';
export const SET_SEARCH_IN_PROGRESS = 'SET_SEARCH_IN_PROGRESS';
export const SET_SEARCH_RESULTS = 'SET_SEARCH_RESULTS';
export const CLEAR_SEARCH = 'CLEAR_SEARCH';
