export const SET_IS_TOKEN_RECEIVED = 'SET_IS_TOKEN_RECEIVED';
export const SET_TOKEN_EXPIRATION_TIME = 'SET_TOKEN_EXPIRATION_TIME';
export const SET_IS_FETCHING_IN_PROGRESS = 'SET_IS_FETCHING_IN_PROGRESS';
export const SET_FETCHING_ERROR = 'SET_FETCHING_ERROR';

export const SET_THEME = 'SET_THEME';

export const SET_GEO_DETECTION_POSITION = 'SET_GEO_DETECTION_POSITION';
export const SET_GEO_DETECTION_ERROR = 'SET_GEO_DETECTION_ERROR';
