export const SET_IS_TOKEN_RECEIVED = 'SET_IS_TOKEN_RECEIVED';
export const SET_TOKEN_EXPIRATION_TIME = 'SET_TOKEN_EXPIRATION_TIME';
export const SET_IS_FETCHING_IN_PROGRESS = 'SET_IS_FETCHING_IN_PROGRESS';
export const SET_FETCHING_ERROR = 'SET_FETCHING_ERROR';
