export const FETCH_WEATHER_START = 'FETCH_WEATHER_START';
export const FETCH_WEATHER_SUCCESS = 'FETCH_WEATHER_SUCCESS';
export const FETCH_WEATHER_FAILURE = 'FETCH_WEATHER_FAILURE';

export const SET_CITY_FORECAST = 'SET_CITY_FORECAST';
export const SET_DAILY_CITY_FORECAST = 'SET_DAILY_CITY_FORECAST';
export const SET_HOURLY_CITY_FORECAST = 'SET_HOURLY_CITY_FORECAST';
export const SET_TEMPERATURE_UNIT = 'SET_TEMPERATURE_UNIT';