const capitals = [
    { name: 'athens', id: 1 },
    { name: 'belgrade', id: 2 },
    { name: 'berlin', id: 3 },
    { name: 'bern', id: 4 },
    { name: 'bratislava', id: 5 },
    { name: 'brussels', id: 6 },
    { name: 'bucharest', id: 7 },
    { name: 'budapest', id: 8 },
    { name: 'chisinau', id: 9 },
    { name: 'copenhagen', id: 10 },
    { name: 'dublin', id: 11 },
    { name: 'helsinki', id: 12 },
    { name: 'kiev', id: 13 },
    { name: 'lisbon', id: 14 },
    { name: 'ljubljana', id: 15 },
    { name: 'london', id: 16 },
    { name: 'luxembourg', id: 17 },
    { name: 'madrid', id: 18 },
    { name: 'minsk', id: 19 },
    { name: 'monaco', id: 20 },
    { name: 'moscow', id: 21 },
    { name: 'nicosia', id: 22 },
    { name: 'nuuk', id: 23 },
    { name: 'oslo', id: 24 },
    { name: 'paris', id: 26 },
    { name: 'podgorica', id: 27 },
    { name: 'prague', id: 28 },
    { name: 'reykjavik', id: 29 },
    { name: 'riga', id: 30 },
    { name: 'rome', id: 31 },
    { name: 'san marino', id: 32 },
    { name: 'sarajevo', id: 33 },
    { name: 'skopje', id: 34 },
    { name: 'sofia', id: 35 },
    { name: 'stockholm', id: 36 },
    { name: 'tallinn', id: 37 },
    { name: 'tirana', id: 38 },
    { name: 'vaduz', id: 39 },
    { name: 'valletta', id: 40 },
    { name: 'vatican', id: 41 },
    { name: 'vienna', id: 42 },
    { name: 'vilnius', id: 43 },
    { name: 'warsaw', id: 44 },
    { name: 'zagreb', id: 45 }
  ];
  
  export default capitals;